#!/usr/bin/env bash
# ============================================================================
# CLAUDECLAW — PRODUCTION RUNBOOK
# Complete setup, boot, and operations guide
# Matched to: claudeclaw-os repo (feat/skinwalker-pipeline)
# Updated: May 10, 2026
# ============================================================================

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 1: FIRST TIME SETUP (run once, in order)
# ─────────────────────────────────────────────────────────────────────────────

# 1.1 — Navigate to project
cd /Users/agenthive/claudeclaw-os

# 1.2 — Verify Node.js 20+
node --version
# Expected: v20.x.x or higher

# 1.3 — Install dependencies
npm install

# 1.4 — Run the setup wizard (generates .env, DB encryption key, PIN)
npm run setup
# Follow the prompts. This creates:
#   .env — all config
#   store/claudeclaw.db — SQLite database
#   ~/.claudeclaw/CLAUDE.md — agent system prompt

# 1.5 — Verify build compiles cleanly
npm run typecheck
# Expected: no output (clean exit)

# 1.6 — Verify tests pass
npm test
# Expected: gods-eye tests (12), youtube-analytics tests (4) all pass

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 2: ENVIRONMENT VARIABLES
# All managed in .env (setup wizard creates it). Key vars below.
# ─────────────────────────────────────────────────────────────────────────────

# 2.1 — Required (setup wizard handles these)
# TELEGRAM_BOT_TOKEN=         — from @BotFather
# ALLOWED_CHAT_ID=            — your Telegram chat ID
# DB_ENCRYPTION_KEY=          — auto-generated 32-byte hex

# 2.2 — God's Eye Pipeline (add manually)
# YOUTUBE_API_KEY=            — Google Cloud Console → YouTube Data API v3
# GOOGLE_API_KEY=             — Google AI Studio → for Gemini analysis

# 2.3 — YouTube Analytics (OAuth2, for return viewer rate)
# YT_ANALYTICS_CLIENT_ID=    — Google Cloud Console → OAuth 2.0 Client ID
# YT_ANALYTICS_CLIENT_SECRET= — from same credential
# YT_ANALYTICS_TOKEN_PATH=~/.config/youtube-analytics/token.json

# 2.4 — Skinwalker Production
# ELEVENLABS_API_KEY=         — elevenlabs.io
# ELEVENLABS_VOICE_ID=        — your cloned voice ID
# HEYGEN_API_KEY=             — heygen.com

# 2.5 — Dashboard
# DASHBOARD_TOKEN=            — auto-generated by setup wizard
# DASHBOARD_PORT=3141

# 2.6 — Verify all critical vars are set
grep -c "=" .env
# Expected: 10+ lines (varies by how many integrations you've configured)

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 3: FIRST BOOT — Initialize & verify database
# ─────────────────────────────────────────────────────────────────────────────

# 3.1 — Boot the bot (creates DB + runs migrations on first start)
npm run dev
# Expected: Telegram bot connects, dashboard starts on :3141
# Press Ctrl+C after confirming it boots cleanly

# 3.2 — Verify database was created
ls -lh store/claudeclaw.db
# Expected: file present, size > 0

# 3.3 — Verify key tables exist
sqlite3 store/claudeclaw.db ".tables"
# Expected: youtube_videos, youtube_analytics, channel_snapshots,
#   hive_mind, memories, conversation_log, token_usage, scheduled_tasks,
#   production_log, avatar_registry, voice_registry, and ~30 more

# 3.4 — Verify channel_snapshots has returning viewer columns
sqlite3 store/claudeclaw.db "PRAGMA table_info(channel_snapshots);" | grep -E "returning|new_viewer"
# Expected: two rows — returning_viewer_pct and new_viewer_pct

# 3.5 — Verify foreign key integrity
sqlite3 store/claudeclaw.db "PRAGMA integrity_check;"
# Expected: ok

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 4: YOUTUBE ANALYTICS OAUTH2 (one-time consent flow)
# ─────────────────────────────────────────────────────────────────────────────

# 4.1 — Prerequisites:
#   a) Go to console.cloud.google.com → APIs & Services → Credentials
#   b) Create OAuth 2.0 Client ID (type: Desktop app)
#   c) Enable "YouTube Analytics API" in your project
#   d) Add client ID + secret to .env:
#      YT_ANALYTICS_CLIENT_ID=your-id.apps.googleusercontent.com
#      YT_ANALYTICS_CLIENT_SECRET=your-secret

# 4.2 — Run the auth flow
npx tsx scripts/yt-analytics-auth.ts
# Opens browser → authorize → token saved to ~/.config/youtube-analytics/token.json

# 4.3 — Verify token was saved
ls -la ~/.config/youtube-analytics/token.json
# Expected: file present, permissions 600

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 5: GOD'S EYE — First Analysis
# ─────────────────────────────────────────────────────────────────────────────

# 5.1 — Analyze a channel via the pipeline CLI
npx tsx scripts/pipeline-cli.ts analyze @ChloeVsHistory --niche comedy --json
# Expected: JSON brief with hook_analysis, emotional_arc, top_patterns, competitor_gaps

# 5.2 — Verify videos were ingested into Hive Mind
sqlite3 store/claudeclaw.db "SELECT COUNT(*) FROM youtube_videos;"
# Expected: number > 0

# 5.3 — Check channel snapshot (if YouTube Analytics OAuth is configured)
sqlite3 store/claudeclaw.db "SELECT channel_id, snapshot_date, returning_viewer_pct, new_viewer_pct FROM channel_snapshots ORDER BY snapshot_date DESC LIMIT 5;"

# 5.4 — Score a concept before production
npx tsx scripts/pipeline-cli.ts score @ChloeVsHistory --title "Why Everyone Is Wrong About This" --niche comedy
# Expected: 0-100 score with matched/missing patterns

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 6: SCHEMA VERIFICATION (run after first boot or migration)
# ─────────────────────────────────────────────────────────────────────────────

# 6.1 — God's Eye tables
sqlite3 store/claudeclaw.db "SELECT COUNT(*) as videos FROM youtube_videos;"
sqlite3 store/claudeclaw.db "SELECT COUNT(*) as analytics FROM youtube_analytics;"
sqlite3 store/claudeclaw.db "SELECT COUNT(*) as retention FROM youtube_viewer_retention;"
sqlite3 store/claudeclaw.db "SELECT COUNT(*) as snapshots FROM channel_snapshots;"

# 6.2 — Production tables
sqlite3 store/claudeclaw.db "SELECT COUNT(*) FROM production_log;"
sqlite3 store/claudeclaw.db "SELECT * FROM avatar_registry;"
sqlite3 store/claudeclaw.db "SELECT * FROM voice_registry;"

# 6.3 — Hive Mind activity
sqlite3 store/claudeclaw.db "SELECT agent_id, action, COUNT(*) as entries FROM hive_mind GROUP BY agent_id, action ORDER BY entries DESC LIMIT 10;"

# 6.4 — Check indexes
sqlite3 store/claudeclaw.db "SELECT name FROM sqlite_master WHERE type='index' AND name LIKE 'idx_%' ORDER BY name;" | head -20

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 7: SCHEDULED TASKS (cron via ClaudeClaw's built-in scheduler)
# ClaudeClaw has its own scheduled_tasks table — no system crontab needed.
# Tasks are checked every tick by the running bot process.
# ─────────────────────────────────────────────────────────────────────────────

# 7.1 — View all scheduled tasks
sqlite3 store/claudeclaw.db "SELECT id, prompt, schedule, status, last_status, agent_id FROM scheduled_tasks ORDER BY next_run;"

# 7.2 — Check due tasks (tasks that should run now)
sqlite3 store/claudeclaw.db "SELECT id, prompt, next_run, datetime(next_run, 'unixepoch') as next_run_human FROM scheduled_tasks WHERE status = 'active' AND next_run <= strftime('%s', 'now');"

# 7.3 — Check for stuck tasks (running too long)
sqlite3 store/claudeclaw.db "SELECT id, prompt, started_at, datetime(started_at, 'unixepoch') as started_human FROM scheduled_tasks WHERE status = 'running';"

# 7.4 — Reset stuck tasks (if any show as 'running' for hours)
# sqlite3 store/claudeclaw.db "UPDATE scheduled_tasks SET status = 'active', started_at = NULL WHERE status = 'running';"

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 8: DAILY OPERATIONS — Commands you'll run regularly
# ─────────────────────────────────────────────────────────────────────────────

# 8.1 — Start the bot (foreground, for development)
npm run dev

# 8.2 — Start the bot (background, for production via launchd)
# See claudeclaw.plist for launchd config

# 8.3 — Re-analyze a channel (force fresh data)
npx tsx scripts/pipeline-cli.ts analyze @ChloeVsHistory --niche comedy --force

# 8.4 — View top patterns by confidence
sqlite3 store/claudeclaw.db "
  SELECT video_id, title, view_count, like_count,
    ROUND(CAST(like_count AS REAL) / NULLIF(view_count, 0) * 100, 2) as engagement_pct
  FROM youtube_videos
  ORDER BY view_count DESC
  LIMIT 10;
"

# 8.5 — Check Hive Mind recent activity
sqlite3 store/claudeclaw.db "
  SELECT agent_id, action,
    SUBSTR(summary, 1, 80) as summary,
    datetime(created_at, 'unixepoch') as when_
  FROM hive_mind
  ORDER BY created_at DESC
  LIMIT 10;
"

# 8.6 — Check today's token spend
sqlite3 store/claudeclaw.db "
  SELECT
    agent_id,
    COUNT(*) as turns,
    SUM(input_tokens) as input_tok,
    SUM(output_tokens) as output_tok,
    ROUND(SUM(cost_usd), 4) as cost
  FROM token_usage
  WHERE created_at >= strftime('%s', 'now', 'start of day')
  GROUP BY agent_id
  ORDER BY cost DESC;
"

# 8.7 — View channel snapshot trends
sqlite3 store/claudeclaw.db "
  SELECT snapshot_date, subscriber_count, total_views,
    returning_viewer_pct, new_viewer_pct, health_score
  FROM channel_snapshots
  ORDER BY snapshot_date DESC
  LIMIT 14;
"

# 8.8 — View production history
sqlite3 store/claudeclaw.db "
  SELECT niche, script_title, status, quality_score,
    ROUND(total_cost_usd, 2) as cost,
    datetime(created_at, 'unixepoch') as when_
  FROM production_log
  ORDER BY created_at DESC
  LIMIT 10;
"

# 8.9 — Check memory health
sqlite3 store/claudeclaw.db "
  SELECT
    COUNT(*) as total_memories,
    SUM(CASE WHEN pinned = 1 THEN 1 ELSE 0 END) as pinned,
    ROUND(AVG(importance), 2) as avg_importance,
    ROUND(AVG(salience), 2) as avg_salience
  FROM memories;
"

# 8.10 — View audit log (security events)
sqlite3 store/claudeclaw.db "
  SELECT agent_id, action, blocked,
    SUBSTR(detail, 1, 60) as detail,
    datetime(created_at, 'unixepoch') as when_
  FROM audit_log
  ORDER BY created_at DESC
  LIMIT 15;
"

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 9: PROTOCOL 99 — EMERGENCY KILL SWITCH
# Instant halt of all operations
# ─────────────────────────────────────────────────────────────────────────────

# 9.1 — Emergency kill phrase (configured in .env)
# Send EMERGENCY_KILL_PHRASE to ANY bot → all agents stop, process exits
# This is the fastest kill path — works from your phone via Telegram

# 9.2 — Manual emergency: pause all scheduled tasks
sqlite3 store/claudeclaw.db "UPDATE scheduled_tasks SET status = 'paused' WHERE status = 'active';"
echo "⚠️  All scheduled tasks paused."

# 9.3 — Cancel all running missions
sqlite3 store/claudeclaw.db "UPDATE mission_tasks SET status = 'cancelled', completed_at = strftime('%s', 'now') WHERE status IN ('queued', 'running');"
echo "⚠️  All missions cancelled."

# 9.4 — Log the emergency to audit trail
sqlite3 store/claudeclaw.db "INSERT INTO audit_log (agent_id, chat_id, action, detail, blocked, created_at) VALUES ('operator', '', 'protocol_99', 'Manual emergency halt via runbook', 0, strftime('%s', 'now'));"

# 9.5 — Resume after emergency
sqlite3 store/claudeclaw.db "UPDATE scheduled_tasks SET status = 'active' WHERE status = 'paused';"
echo "✅ Scheduled tasks resumed."

# 9.6 — View Protocol 99 history
sqlite3 store/claudeclaw.db "SELECT datetime(created_at, 'unixepoch') as when_, detail FROM audit_log WHERE action = 'protocol_99' ORDER BY created_at DESC;"

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 10: BACKUP
# ─────────────────────────────────────────────────────────────────────────────

# 10.1 — Create backup directory
mkdir -p backups

# 10.2 — Backup Hive Mind database with timestamp
cp store/claudeclaw.db "backups/claudeclaw_$(date +%Y%m%d_%H%M%S).db"
echo "✅ Database backed up."

# 10.3 — Backup .env and agent configs
cp .env "backups/env_$(date +%Y%m%d_%H%M%S).bak"
cp -r ~/.claudeclaw "backups/claudeclaw_config_$(date +%Y%m%d_%H%M%S)"

# 10.4 — List backups
ls -lh backups/

# 10.5 — Restore from backup (stop bot first!)
# cp backups/claudeclaw_YYYYMMDD_HHMMSS.db store/claudeclaw.db

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 11: SYSTEM STATUS — Full health check
# ─────────────────────────────────────────────────────────────────────────────

echo "=== CLAUDECLAW — SYSTEM STATUS ===" && \
echo "" && \
echo "--- Database ---" && \
sqlite3 store/claudeclaw.db "SELECT 'Tables: ' || COUNT(*) FROM sqlite_master WHERE type='table';" && \
sqlite3 store/claudeclaw.db "SELECT 'YouTube videos: ' || COUNT(*) FROM youtube_videos;" && \
sqlite3 store/claudeclaw.db "SELECT 'Channel snapshots: ' || COUNT(*) FROM channel_snapshots;" && \
sqlite3 store/claudeclaw.db "SELECT 'Hive Mind entries: ' || COUNT(*) FROM hive_mind;" && \
sqlite3 store/claudeclaw.db "SELECT 'Memories: ' || COUNT(*) || ' (pinned: ' || SUM(CASE WHEN pinned=1 THEN 1 ELSE 0 END) || ')' FROM memories;" && \
sqlite3 store/claudeclaw.db "SELECT 'Productions: ' || COUNT(*) FROM production_log;" && \
echo "" && \
echo "--- Costs (today) ---" && \
sqlite3 store/claudeclaw.db "SELECT COALESCE('$' || ROUND(SUM(cost_usd), 2), '\$0.00') || ' across ' || COUNT(*) || ' turns' FROM token_usage WHERE created_at >= strftime('%s', 'now', 'start of day');" && \
echo "" && \
echo "--- Scheduled Tasks ---" && \
sqlite3 store/claudeclaw.db "SELECT status, COUNT(*) FROM scheduled_tasks GROUP BY status;" && \
echo "" && \
echo "--- Missions ---" && \
sqlite3 store/claudeclaw.db "SELECT status, COUNT(*) FROM mission_tasks GROUP BY status;" && \
echo "" && \
echo "=== STATUS CHECK COMPLETE ==="

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 12: TROUBLESHOOTING
# ─────────────────────────────────────────────────────────────────────────────

# 12.1 — Bot won't start
npm run dev
# Check: .env exists? TELEGRAM_BOT_TOKEN set? DB_ENCRYPTION_KEY set?
# Check: node --version >= 20? npm install run?

# 12.2 — God's Eye returns no data
echo $YOUTUBE_API_KEY
# Check: key not empty? YouTube quota not exhausted?
# Check quota: console.cloud.google.com → APIs & Services → YouTube Data API v3 → Quotas

# 12.3 — YouTube Analytics returns 403
# Check: OAuth token expired? Re-run: npx tsx scripts/yt-analytics-auth.ts
# Check: "YouTube Analytics API" enabled in Google Cloud project?

# 12.4 — Database locked errors
sqlite3 store/claudeclaw.db "PRAGMA journal_mode;"
# Expected: wal
# If not WAL mode, the bot startup migration didn't run — restart bot

# 12.5 — Memory decay not running
sqlite3 store/claudeclaw.db "SELECT COUNT(*) FROM memories WHERE salience < 0.1 AND pinned = 0;"
# If high count: decay is working but cleanup isn't. Restart bot process.

# 12.6 — Dashboard won't load
curl -s http://localhost:3141/api/health
# Check: DASHBOARD_TOKEN set? DASHBOARD_PORT=3141 not in use?

# 12.7 — TypeScript won't compile
npm run typecheck
# Look for specific file:line errors and fix

# 12.8 — Nuclear option: wipe DB and start fresh (WARNING: destroys all data)
# rm store/claudeclaw.db
# npm run dev
# (database recreated on boot)

# 12.9 — Check database integrity
sqlite3 store/claudeclaw.db "PRAGMA integrity_check;"
# Expected: ok

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 13: DASHBOARD ACCESS
# ─────────────────────────────────────────────────────────────────────────────

# 13.1 — Local access
# http://localhost:3141?token=YOUR_DASHBOARD_TOKEN

# 13.2 — Remote access (via Cloudflare Tunnel)
# Set DASHBOARD_URL in .env to your tunnel URL
# Access: https://your-tunnel.trycloudflare.com?token=YOUR_DASHBOARD_TOKEN

# 13.3 — Dashboard features
# • Memory explorer (importance, salience, pinned)
# • Token usage & cost tracking
# • Mission Control (create, assign, track tasks)
# • Agent file editor (CLAUDE.md, agent.yaml)
# • War Room (voice/text multi-agent meetings)
# • Conversation history viewer

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 14: PRODUCTION PIPELINE — End to End
# ─────────────────────────────────────────────────────────────────────────────

# 14.1 — Full pipeline: analyze → script → score → produce
npx tsx scripts/pipeline-cli.ts produce @ChloeVsHistory --niche comedy

# 14.2 — Just analyze + script (no render)
npx tsx scripts/pipeline-cli.ts script @ChloeVsHistory --niche comedy

# 14.3 — Check production tracker after render
sqlite3 store/claudeclaw.db "
  SELECT script_title, status, avatar_id, voice_id,
    ROUND(total_cost_usd, 2) as cost,
    ROUND(render_time_seconds, 0) as render_secs,
    quality_score
  FROM production_log
  ORDER BY created_at DESC LIMIT 5;
"

# 14.4 — View avatar/voice consistency per niche
sqlite3 store/claudeclaw.db "SELECT niche, avatar_id, avatar_name, provider FROM avatar_registry;"
sqlite3 store/claudeclaw.db "SELECT niche, voice_id, voice_name, provider FROM voice_registry;"

# ─────────────────────────────────────────────────────────────────────────────
# END OF RUNBOOK
# ─────────────────────────────────────────────────────────────────────────────
